# Helpers for construct_matrices! determining whether the geometry cache must
# include the log(w') correction associated with nontrivial Kress grading.
@inline _is_kress_graded(::CFIE_kress,pts::Vector{<:BoundaryPoints})=false
@inline _is_kress_graded(::CFIE_kress_corners,pts::Vector{<:BoundaryPoints})=any(_is_nontrivial_grading,pts)
@inline _is_kress_graded(::CFIE_kress_global_corners,pts::Vector{<:BoundaryPoints})=any(_is_nontrivial_grading,pts)

"""
    ReducedOrbitInfo{T}

Precomputed symmetry-orbit metadata for one reduced boundary degree of freedom.

## Description
In a symmetry-reduced boundary discretization, a single reduced unknown
represents a complete orbit of full-boundary nodes generated by the active
symmetry group.

If the full orbit associated with one representative is

    {g₁,g₂,...,g_m},

with symmetry weights

    {χ₁,χ₂,...,χ_m},

then a reduced matrix entry is assembled as

    A_red(a,b)=∑ₗ χₗ A_full(i_a,jₗ),

where `i_a` is the full representative of reduced row `a` and `jₗ` runs over
the orbit associated with reduced column `b`.

This structure caches both the global orbit indices and their component-local
coordinates, avoiding repeated symmetry-map reconstruction during matrix
assembly.

## Attributes
* `redidx`: Reduced index associated with the orbit representative.
* `full`: Full global boundary indices belonging to the orbit.
* `scales`: Symmetry scaling factors multiplying the orbit contributions.
* `cscales`: Complex conjugates of `scales`, useful for adjoint formulations.
* `blocks`: Connected boundary-component index associated with each orbit node.
* `locals`: Local index of each orbit node inside its corresponding component.
"""
struct ReducedOrbitInfo{T<:Real}
    redidx::Int
    full::Vector{Int}
    scales::Vector{Complex{T}}
    cscales::Vector{Complex{T}}
    blocks::Vector{Int}
    locals::Vector{Int}
end

"""
    build_reduced_orbit_infos(Ifund,full_to_fund,fund_to_full,fund_to_scale,
        global_to_block,global_to_local) → infos

Constructs cached symmetry-orbit metadata for reduced CFIE-Kress assembly.

## Description
The raw symmetry bookkeeping is converted into one [`ReducedOrbitInfo`](@ref)
object per reduced degree of freedom.

For every reduced source index, the resulting object stores:
* the complete full-boundary orbit,
* its symmetry scaling factors,
* conjugated scaling factors,
* connected-component ownership,
* local component indices.

These quantities are then reused directly by the reduced matrix assembly
kernels.

## Arguments
* `Ifund`: Full-boundary representative index for every reduced degree of
  freedom.
* `full_to_fund`: Mapping from every full index to its reduced index.
* `fund_to_full`: Full symmetry orbit associated with each reduced index.
* `fund_to_scale`: Symmetry factors associated with the entries of each orbit.
* `global_to_block`: Mapping from a global boundary index to its connected
  component.
* `global_to_local`: Mapping from a global boundary index to its local index
  inside that component.

## Returns
* `infos`: Vector of [`ReducedOrbitInfo`](@ref), one entry per reduced degree of
  freedom.
"""
function build_reduced_orbit_infos(Ifund::Vector{Int},full_to_fund::Vector{Int},fund_to_full::Vector{Vector{Int}},fund_to_scale::Vector{Vector{Complex{T}}},global_to_block::Vector{Int},global_to_local::Vector{Int}) where {T<:Real}
    n=length(Ifund)
    infos=Vector{ReducedOrbitInfo{T}}(undef,n)
    @inbounds for a in 1:n
        g0=Ifund[a]
        orbit=fund_to_full[a]
        scales=fund_to_scale[a]
        m=length(orbit)
        blocks=Vector{Int}(undef,m)
        locals=Vector{Int}(undef,m)
        cscales=Vector{Complex{T}}(undef,m)
        for q in 1:m
            g=orbit[q]
            blocks[q]=global_to_block[g]
            locals[q]=global_to_local[g]
            cscales[q]=conj(scales[q])
        end
        infos[a]=ReducedOrbitInfo{T}(full_to_fund[g0],orbit,scales,cscales,blocks,locals)
    end
    return infos
end

"""
    cfie_reduced_orbit_size(solver,pts) → nfund

Returns the matrix dimension after symmetry reduction.

## Description
If no symmetry is active, the result is simply the complete boundary matrix
dimension.

With symmetry, the complete set of boundary indices is partitioned into
symmetry orbits. One representative is retained from each orbit, so the number
of orbits determines the reduced matrix dimension.

## Arguments
* `solver`: CFIE solver whose optional `symmetry` field determines the symmetry
  reduction.
* `pts`: Boundary discretizations for all connected components.

## Returns
* `nfund`: Number of independent symmetry-orbit representatives.
"""
function cfie_reduced_orbit_size(solver::Union{CFIE_kress,CFIE_kress_corners,CFIE_kress_global_corners,CFIE_alpert},pts::Vector{BoundaryPoints{T}}) where {T<:Real}
    isnothing(solver.symmetry)&&return boundary_matrix_size(pts)
    maps=build_symmetry_maps(pts,solver.symmetry)
    N=boundary_matrix_size(pts)
    visited=falses(N)
    nfund=0
    @inbounds for g in 1:N
        visited[g]&&continue
        orb=apply_symmetry_orbit_from_maps(maps,solver.symmetry,g)
        nfund+=1
        for gg in orb.indices
            visited[gg]=true
        end
    end
    return nfund
end

"""
    CFIEKressWorkspace{T,M,S}

Reusable geometry and symmetry cache for CFIE-Kress matrix assembly.

## Description
This workspace contains all quantities that depend on the fixed boundary
discretization but not on the current wavenumber `k`.

For a boundary consisting of several connected components, each component has
its own:
* Kress logarithmic correction block,
* pairwise geometry cache,
* flattened panel geometry arrays.

The global matrix is ordered component by component. `offs` stores the mapping
between each component's local indices and the global matrix indices.

If symmetry is active, the workspace additionally stores the complete
full-to-reduced and reduced-to-full orbit maps required for direct assembly of
the reduced matrix without first constructing the full complex operator.

## Attributes
* `offs`: Component offsets into the full matrix.
* `Rmat`: Global block-diagonal Kress logarithmic correction matrix.
* `Gs`: One [`BoundaryGeomCache`](@ref) for each connected boundary component.
* `parr`: One [`BoundaryPanelArrays`](@ref) cache for each connected component.
* `Ntot`: Full matrix dimension.
* `symmetry`: Active symmetry descriptor, or `nothing`.
* `Nred`: Reduced matrix dimension when symmetry is active, otherwise `Ntot`.
* `Ifund`: Full-boundary representatives of the reduced symmetry orbits.
* `full_to_fund`: Mapping from every full index to its reduced index.
* `full_to_scale`: Symmetry scale associated with every full index.
* `fund_to_full`: Full orbit associated with each reduced degree of freedom.
* `fund_to_scale`: Symmetry scales associated with each full orbit.
* `global_to_block`: Mapping from each global index to its boundary component.
* `global_to_local`: Mapping from each global index to its local component index.
* `reduced_orbits`: Precomputed symmetry-orbit metadata used during reduced
  assembly.
"""
struct CFIEKressWorkspace{T<:Real,M<:AbstractMatrix{T},S}
    offs::Vector{Int}
    Rmat::M
    Gs::Vector{BoundaryGeomCache{T}}
    parr::Vector{BoundaryPanelArrays{T}}
    Ntot::Int
    symmetry::S
    Nred::Int
    Ifund::Vector{Int}
    full_to_fund::Vector{Int}
    full_to_scale::Vector{Complex{T}}
    fund_to_full::Vector{Vector{Int}}
    fund_to_scale::Vector{Vector{Complex{T}}}
    global_to_block::Vector{Int}
    global_to_local::Vector{Int}
    reduced_orbits::Vector{ReducedOrbitInfo{T}}
end

"""
    build_cfie_kress_workspace(solver,pts) → ws

Builds a reusable CFIE-Kress workspace for a fixed boundary discretization.

## Description
The builder constructs:
1. component offsets,
2. the global block-diagonal Kress correction matrix,
3. one geometry cache per connected component,
4. one flattened panel-array cache per connected component,
5. global-to-component index maps,
6. symmetry-orbit metadata when symmetry is active.

For graded components, [`boundary_geom_cache`](@ref) is constructed with the
grading-aware logarithmic correction enabled. Smooth components use the ordinary
periodic logarithmic cache.

## Arguments
* `solver`: Smooth, single-curve graded, or global-corner CFIE-Kress solver.
* `pts`: Boundary discretizations for all connected components.

## Returns
* `ws`: Reusable [`CFIEKressWorkspace`](@ref).
"""
function build_cfie_kress_workspace(solver::Union{CFIE_kress,CFIE_kress_corners,CFIE_kress_global_corners},pts::Vector{BoundaryPoints{T}}) where {T<:Real}
    offs=component_offsets(pts)
    Rmat=build_Rmat_kress(solver,pts)
    Gs=[boundary_geom_cache(p,_is_nontrivial_grading(p)) for p in pts]
    parr=[_boundary_panel_arrays_cache(p) for p in pts]
    Ntot=offs[end]-1
    g2c,g2l=global_to_component_local(pts)
    if isnothing(solver.symmetry)
        Ifund=collect(1:Ntot)
        full_to_fund=collect(1:Ntot)
        full_to_scale=ones(Complex{T},Ntot)
        fund_to_full=[[i] for i in 1:Ntot]
        fund_to_scale=[[one(Complex{T})] for _ in 1:Ntot]
        reduced_orbits=build_reduced_orbit_infos(Ifund,full_to_fund,fund_to_full,fund_to_scale,g2c,g2l)
        return CFIEKressWorkspace(offs,Rmat,Gs,parr,Ntot,nothing,Ntot,Ifund,full_to_fund,full_to_scale,fund_to_full,fund_to_scale,g2c,g2l,reduced_orbits)
    end
    sym=solver.symmetry
    maps=build_symmetry_maps(pts,sym)
    Ifund=Int[]
    full_to_fund=zeros(Int,Ntot)
    full_to_scale=zeros(Complex{T},Ntot)
    fund_to_full=Vector{Vector{Int}}()
    fund_to_scale=Vector{Vector{Complex{T}}}()
    visited=falses(Ntot)
    @inbounds for g in 1:Ntot
        visited[g]&&continue
        orb=apply_symmetry_orbit_from_maps(maps,sym,g)
        inds=orb.indices
        scales=Complex{T}.(orb.scales)
        push!(Ifund,g)
        b=length(Ifund)
        push!(fund_to_full,inds)
        push!(fund_to_scale,scales)
        for q in eachindex(inds)
            gg=inds[q]
            visited[gg]=true
            full_to_fund[gg]=b
            full_to_scale[gg]=scales[q]
        end
    end
    reduced_orbits=build_reduced_orbit_infos(Ifund,full_to_fund,fund_to_full,fund_to_scale,g2c,g2l)
    return CFIEKressWorkspace(offs,Rmat,Gs,parr,Ntot,sym,length(Ifund),Ifund,full_to_fund,full_to_scale,fund_to_full,fund_to_scale,g2c,g2l,reduced_orbits)
end

"""
    build_Rmat_kress(solver::CFIE_kress,pts) → Rmat

Builds the global periodic Kress logarithmic correction matrix.

## Description
For one smooth periodic component, the logarithmically singular kernel depends
on the periodic parameter difference through

    log(4sin²((t-s)/2)).

Its discrete quadrature correction is represented by the Kress matrix `R`.

For several disconnected components, the logarithmic singularity occurs only
for same-component interactions. The global correction matrix is therefore
block diagonal:

    R=diag(R₁,R₂,...,R_nc).

## Arguments
* `solver`: Smooth periodic CFIE-Kress solver.
* `pts`: One boundary discretization per connected smooth component.

## Returns
* `Rmat`: Global block-diagonal Kress correction matrix.
"""
function build_Rmat_kress(solver::CFIE_kress,pts::Vector{BoundaryPoints{T}}) where {T<:Real}
    offs=component_offsets(pts)
    Ntot=offs[end]-1
    Rmat=zeros(T,Ntot,Ntot)
    for a in eachindex(pts)
        ra=offs[a]:(offs[a+1]-1)
        kress_R!(@view Rmat[ra,ra])
    end
    return Rmat
end

"""
    build_Rmat_kress(solver::Union{CFIE_kress_corners,CFIE_kress_global_corners},pts) → Rmat

Builds the global Kress correction matrix for corner-capable CFIE formulations.

## Description
Every connected component contributes one diagonal block.

If a component is genuinely graded, its logarithmic correction is generated
with [`kress_R_corner!`](@ref). If its grading map is trivial, the ordinary
periodic [`kress_R!`](@ref) block is used.

Thus mixed geometries containing both smooth and graded components are handled
component by component.

## Arguments
* `solver`: Corner-capable CFIE-Kress solver.
* `pts`: Boundary discretizations for all connected components.

## Returns
* `Rmat`: Global block-diagonal Kress correction matrix.
"""
function build_Rmat_kress(solver::Union{CFIE_kress_corners,CFIE_kress_global_corners},pts::Vector{BoundaryPoints{T}}) where {T<:Real}
    offs=component_offsets(pts)
    Ntot=offs[end]-1
    Rmat=zeros(T,Ntot,Ntot)
    for a in eachindex(pts)
        ra=offs[a]:(offs[a+1]-1)
        if _is_nontrivial_grading(pts[a])
            kress_R_corner!(@view Rmat[ra,ra])
        else
            kress_R!(@view Rmat[ra,ra])
        end
    end
    return Rmat
end

"""
    construct_matrices!(solver,A,pts,Rmat,Gs,parr,offs,k;multithreaded=true) → A

Assembles the full CFIE-Kress Fredholm matrix.

## Description
The assembled operator is

    A(k)=I-(D(k)+ikS(k)),

where `D` and `S` are respectively the Helmholtz double-layer and single-layer
boundary operators.

Same-component interactions use the Kress logarithmic splitting. Inter-component
interactions are smooth and are therefore evaluated directly with the ordinary
quadrature weights.

## Arguments
* `solver`: CFIE-Kress solver.
* `A`: Preallocated full complex destination matrix.
* `pts`: Boundary discretizations for all connected components.
* `Rmat`: Global block-diagonal Kress logarithmic correction matrix.
* `Gs`: Geometry caches for the individual connected components.
* `parr`: Flattened panel-array caches for the individual components.
* `offs`: Component offsets into the global matrix.
* `k`: Real wavenumber.

## Keyword arguments
* `multithreaded`: Whether to thread sufficiently large assembly loops.

## Returns
* `A`: Assembled full CFIE-Kress Fredholm matrix.
"""
function construct_matrices!(solver::Union{CFIE_kress,CFIE_kress_corners,CFIE_kress_global_corners},A::AbstractMatrix{Complex{T}},pts::Vector{BoundaryPoints{T}},Rmat::AbstractMatrix{T},Gs::Vector{BoundaryGeomCache{T}},parr::Vector{BoundaryPanelArrays{T}},offs::Vector{Int},k::T;multithreaded::Bool=true) where {T<:Real}
    αL1=-k*inv_two_pi
    αL2=Complex{T}(0,k/2)
    αM1=-inv_two_pi
    αM2=Complex{T}(0,one(T)/2)
    ik=Complex{T}(0,k)
    fill!(A,zero(Complex{T}))
    nc=length(pts)
    for a in 1:nc
        pa=pts[a]
        Ga=Gs[a]
        Pa=parr[a]
        Na=length(Pa.X)
        ra=offs[a]:(offs[a+1]-1)
        @inbounds for i in 1:Na
            gi=ra[i]
            si=Ga.speed[i]
            κi=Ga.kappa[i]
            wi=pa.ws[i]
            dval=Complex{T}(wi*κi,zero(T))
            m1=αM1*si
            m2=((Complex{T}(0,one(T)/2)-euler_over_pi)-inv_two_pi*log((k^2/4)*si^2))*si
            sval=Complex{T}(Rmat[gi,gi]*m1,zero(T))+wi*m2
            A[gi,gi]=one(Complex{T})-(dval+ik*sval)
        end
        @use_threads multithreading=(multithreaded&&Na>=32) for j in 2:Na
            gj=ra[j]
            sj=Ga.speed[j]
            wj=pa.ws[j]
            @inbounds for i in 1:j-1
                gi=ra[i]
                si=Ga.speed[i]
                wi=pa.ws[i]
                r=Ga.R[i,j]
                invr=Ga.invR[i,j]
                lt=Ga.logterm[i,j]
                inn_ij=Ga.inner[i,j]
                inn_ji=Ga.inner[j,i]
                h0,h1=hankel_pair01(k*r)
                j0=real(h0)
                j1=real(h1)
                l1_ij=αL1*inn_ij*j1*invr
                l2_ij=αL2*inn_ij*h1*invr-l1_ij*lt
                dval_ij=Rmat[gi,gj]*l1_ij+wj*l2_ij
                m1_ij=αM1*j0*sj
                m2_ij=αM2*h0*sj-m1_ij*lt
                sval_ij=Rmat[gi,gj]*m1_ij+wj*m2_ij
                A[gi,gj]=-(dval_ij+ik*sval_ij)
                l1_ji=αL1*inn_ji*j1*invr
                l2_ji=αL2*inn_ji*h1*invr-l1_ji*lt
                dval_ji=Rmat[gj,gi]*l1_ji+wi*l2_ji
                m1_ji=αM1*j0*si
                m2_ji=αM2*h0*si-m1_ji*lt
                sval_ji=Rmat[gj,gi]*m1_ji+wi*m2_ji
                A[gj,gi]=-(dval_ji+ik*sval_ji)
            end
        end
    end
    for a in 1:nc,b in 1:nc
        a==b&&continue
        pa=pts[a]
        pb=pts[b]
        Pa=parr[a]
        Pb=parr[b]
        Na=length(Pa.X)
        Nb=length(Pb.X)
        ra=offs[a]:(offs[a+1]-1)
        rb=offs[b]:(offs[b+1]-1)
        Xa=Pa.X;Ya=Pa.Y
        Xb=Pb.X;Yb=Pb.Y
        dXb=Pb.dX;dYb=Pb.dY;sb=Pb.s
        @use_threads multithreading=(multithreaded&&Na>=16) for i in 1:Na
            gi=ra[i]
            xi=Xa[i]
            yi=Ya[i]
            @inbounds for j in 1:Nb
                gj=rb[j]
                dx=xi-Xb[j]
                dy=yi-Yb[j]
                r2=muladd(dx,dx,dy*dy)
                r2<=(eps(T))^2&&continue
                r=sqrt(r2)
                invr=inv(r)
                inn=dYb[j]*dx-dXb[j]*dy
                h0,h1=hankel_pair01(k*r)
                sj=sb[j]
                wj=pb.ws[j]
                dval=wj*(αL2*inn*h1*invr)
                sval=wj*(αM2*h0*sj)
                A[gi,gj]=-(dval+ik*sval)
            end
        end
    end
    return A
end

"""
    construct_matrices_reduced!(solver,A,pts,ws,k;multithreaded=true) → A

Assembles the CFIE-Kress matrix directly in the symmetry-reduced basis.

## Description
Each reduced source degree of freedom represents a complete full-boundary
symmetry orbit. For reduced column `b`, all full-space images stored in
`ws.reduced_orbits[b]` are accumulated with their corresponding character or
phase factors.

Same-component terms retain the complete Kress logarithmic treatment.
Interactions between distinct connected components are regular and evaluated
directly.

The full complex matrix is never constructed.

## Arguments
* `solver`: CFIE-Kress solver with active symmetry.
* `A`: Preallocated reduced `Nred×Nred` matrix.
* `pts`: Full boundary discretizations.
* `ws`: CFIE-Kress workspace containing symmetry-orbit metadata.
* `k`: Real wavenumber.

## Keyword arguments
* `multithreaded`: Whether to thread reduced column assembly.

## Returns
* `A`: Symmetry-reduced CFIE-Kress matrix.
"""
function construct_matrices_reduced!(solver::Union{CFIE_kress,CFIE_kress_corners,CFIE_kress_global_corners},A::AbstractMatrix{Complex{T}},pts::Vector{BoundaryPoints{T}},ws::CFIEKressWorkspace{T},k::T;multithreaded::Bool=true) where {T<:Real}
    Nred=ws.Nred
    @assert size(A,1)==Nred&&size(A,2)==Nred
    αL1=-k*inv_two_pi
    αL2=Complex{T}(0,k/2)
    αM1=-inv_two_pi
    αM2=Complex{T}(0,one(T)/2)
    ik=Complex{T}(0,k)
    fill!(A,zero(Complex{T}))
    @use_threads multithreading=multithreaded for b in 1:Nred
        orb=ws.reduced_orbits[b]
        imgs=orb.full
        scales=orb.scales
        @inbounds for a in 1:Nred
            gi=ws.Ifund[a]
            ib=ws.global_to_block[gi]
            i=ws.global_to_local[gi]
            acc=zero(Complex{T})
            for q in eachindex(imgs)
                gj=imgs[q]
                scale=scales[q]
                jb=ws.global_to_block[gj]
                j=ws.global_to_local[gj]
                if ib==jb
                    p=pts[ib]
                    G=ws.Gs[ib]
                    si=G.speed[i]
                    sj=G.speed[j]
                    wi=p.ws[i]
                    wj=p.ws[j]
                    if i==j
                        dval=Complex{T}(wi*G.kappa[i],zero(T))
                        m1=αM1*si
                        m2=((Complex{T}(0,one(T)/2)-euler_over_pi)-inv_two_pi*log((k^2/4)*si^2))*si
                        sval=Complex{T}(ws.Rmat[gi,gj]*m1,zero(T))+wi*m2
                        acc+=scale*(one(Complex{T})-(dval+ik*sval))
                    else
                        r=G.R[i,j]
                        invr=G.invR[i,j]
                        lt=G.logterm[i,j]
                        inn=G.inner[i,j]
                        h0,h1=hankel_pair01(k*r)
                        j0=real(h0)
                        j1=real(h1)
                        l1=αL1*inn*j1*invr
                        l2=αL2*inn*h1*invr-l1*lt
                        dval=ws.Rmat[gi,gj]*l1+wj*l2
                        m1=αM1*j0*sj
                        m2=αM2*h0*sj-m1*lt
                        sval=ws.Rmat[gi,gj]*m1+wj*m2
                        acc+=scale*-(dval+ik*sval)
                    end
                else
                    Pi=ws.parr[ib]
                    Pj=ws.parr[jb]
                    pb=pts[jb]
                    dx=Pi.X[i]-Pj.X[j]
                    dy=Pi.Y[i]-Pj.Y[j]
                    r2=muladd(dx,dx,dy*dy)
                    if r2>(eps(T))^2
                        r=sqrt(r2)
                        invr=inv(r)
                        inn=Pj.dY[j]*dx-Pj.dX[j]*dy
                        h0,h1=hankel_pair01(k*r)
                        sj=Pj.s[j]
                        wj=pb.ws[j]
                        dval=wj*(αL2*inn*h1*invr)
                        sval=wj*(αM2*h0*sj)
                        acc+=scale*-(dval+ik*sval)
                    end
                end
            end
            A[a,b]=acc
        end
    end
    return A
end

"""
    construct_matrices!(solver,A,A1,A2,pts,Rmat,Gs,parr,offs,k;multithreaded=true) → A,A1,A2

Assembles the full CFIE-Kress matrix and its first two derivatives with respect
to `k`.

## Description
The function computes

    A(k)=I-(D(k)+ikS(k)),

together with

    A1=dA/dk,

and

    A2=d²A/dk².

Both the same-component Kress split and the smooth inter-component kernels are
differentiated analytically.

## Arguments
* `solver`: CFIE-Kress solver.
* `A`: Destination matrix for the operator.
* `A1`: Destination matrix for its first derivative.
* `A2`: Destination matrix for its second derivative.
* `pts`: Boundary discretizations.
* `Rmat`: Global Kress correction matrix.
* `Gs`: Per-component geometry caches.
* `parr`: Per-component flattened geometry arrays.
* `offs`: Component offsets into the full matrix.
* `k`: Real wavenumber.

## Keyword arguments
* `multithreaded`: Whether to thread sufficiently large assembly loops.

## Returns
* `A`: CFIE-Kress matrix.
* `A1`: First wavenumber derivative.
* `A2`: Second wavenumber derivative.
"""
function construct_matrices!(solver::Union{CFIE_kress,CFIE_kress_corners,CFIE_kress_global_corners},A::AbstractMatrix{Complex{T}},A1::AbstractMatrix{Complex{T}},A2::AbstractMatrix{Complex{T}},pts::Vector{BoundaryPoints{T}},Rmat::AbstractMatrix{T},Gs::Vector{BoundaryGeomCache{T}},parr::Vector{BoundaryPanelArrays{T}},offs::Vector{Int},k::T;multithreaded::Bool=true) where {T<:Real}
    αL1=-k*inv_two_pi
    αL2=Complex{T}(0,k/2)
    αM1=-inv_two_pi
    αM2=Complex{T}(0,one(T)/2)
    ik=Complex{T}(0,k)
    fill!(A,zero(Complex{T}))
    fill!(A1,zero(Complex{T}))
    fill!(A2,zero(Complex{T}))
    nc=length(pts)
    for a in 1:nc
        pa=pts[a]
        Ga=Gs[a]
        Pa=parr[a]
        Na=length(Pa.X)
        ra=offs[a]:(offs[a+1]-1)
        @inbounds for i in 1:Na
            gi=ra[i]
            si=Ga.speed[i]
            κi=Ga.kappa[i]
            wi=pa.ws[i]
            dval=Complex{T}(wi*κi,zero(T))
            m1=αM1*si
            m2=((Complex{T}(0,one(T)/2)-euler_over_pi)-inv_two_pi*log((k^2/4)*si^2))*si
            sval=Complex{T}(Rmat[gi,gi]*m1,zero(T))+wi*m2
            m2_1=-(si/(pi*k))
            m2_2=si/(pi*k^2)
            sval1=wi*m2_1
            sval2=wi*m2_2
            A[gi,gi]=one(Complex{T})-(dval+ik*sval)
            A1[gi,gi]=-(Complex{T}(0,1)*sval+ik*sval1)
            A2[gi,gi]=-(Complex{T}(0,2)*sval1+ik*sval2)
        end
        @use_threads multithreading=(multithreaded&&Na>=32) for j in 2:Na
            gj=ra[j]
            sj=Ga.speed[j]
            wj=pa.ws[j]
            @inbounds for i in 1:j-1
                gi=ra[i]
                si=Ga.speed[i]
                wi=pa.ws[i]
                r=Ga.R[i,j]
                invr=Ga.invR[i,j]
                lt=Ga.logterm[i,j]
                inn_ij=Ga.inner[i,j]
                inn_ji=Ga.inner[j,i]
                kr=k*r
                h0,h1=hankel_pair01(kr)
                j0=real(h0)
                j1=real(h1)
                l1_ij=αL1*inn_ij*j1*invr
                l2_ij=αL2*inn_ij*h1*invr-l1_ij*lt
                dval_ij=Rmat[gi,gj]*l1_ij+wj*l2_ij
                l1_ij_1=-(inn_ij*k*j0)*inv_two_pi
                l1_ij_2=(inn_ij*(k*r*j1-j0))*inv_two_pi
                l2_ij_1=(inn_ij*k*(lt*j0+im*pi*h0))*inv_two_pi
                l2_ij_2=(inn_ij*(lt*(j0-k*r*j1)+im*pi*(h0-k*r*h1)))*inv_two_pi
                dval_ij_1=Rmat[gi,gj]*l1_ij_1+wj*l2_ij_1
                dval_ij_2=Rmat[gi,gj]*l1_ij_2+wj*l2_ij_2
                m1_ij=αM1*j0*sj
                m2_ij=αM2*h0*sj-m1_ij*lt
                sval_ij=Rmat[gi,gj]*m1_ij+wj*m2_ij
                m1_ij_1=(r*sj*j1)*inv_two_pi
                m1_ij_2=(r*sj*(k*r*j0-j1))*inv_two_pi/k
                m2_ij_1=-(r*sj*(lt*j1+im*pi*h1))*inv_two_pi
                m2_ij_2=(r*sj*(lt*(j1-k*r*j0)-im*pi*k*r*h0+im*pi*h1))*inv_two_pi/k
                sval_ij_1=Rmat[gi,gj]*m1_ij_1+wj*m2_ij_1
                sval_ij_2=Rmat[gi,gj]*m1_ij_2+wj*m2_ij_2
                A[gi,gj]=-(dval_ij+ik*sval_ij)
                A1[gi,gj]=-(dval_ij_1+Complex{T}(0,1)*sval_ij+ik*sval_ij_1)
                A2[gi,gj]=-(dval_ij_2+Complex{T}(0,2)*sval_ij_1+ik*sval_ij_2)
                l1_ji=αL1*inn_ji*j1*invr
                l2_ji=αL2*inn_ji*h1*invr-l1_ji*lt
                dval_ji=Rmat[gj,gi]*l1_ji+wi*l2_ji
                l1_ji_1=-(inn_ji*k*j0)*inv_two_pi
                l1_ji_2=(inn_ji*(k*r*j1-j0))*inv_two_pi
                l2_ji_1=(inn_ji*k*(lt*j0+im*pi*h0))*inv_two_pi
                l2_ji_2=(inn_ji*(lt*(j0-k*r*j1)+im*pi*(h0-k*r*h1)))*inv_two_pi
                dval_ji_1=Rmat[gj,gi]*l1_ji_1+wi*l2_ji_1
                dval_ji_2=Rmat[gj,gi]*l1_ji_2+wi*l2_ji_2
                m1_ji=αM1*j0*si
                m2_ji=αM2*h0*si-m1_ji*lt
                sval_ji=Rmat[gj,gi]*m1_ji+wi*m2_ji
                m1_ji_1=(r*si*j1)*inv_two_pi
                m1_ji_2=(r*si*(k*r*j0-j1))*inv_two_pi/k
                m2_ji_1=-(r*si*(lt*j1+im*pi*h1))*inv_two_pi
                m2_ji_2=(r*si*(lt*(j1-k*r*j0)-im*pi*k*r*h0+im*pi*h1))*inv_two_pi/k
                sval_ji_1=Rmat[gj,gi]*m1_ji_1+wi*m2_ji_1
                sval_ji_2=Rmat[gj,gi]*m1_ji_2+wi*m2_ji_2
                A[gj,gi]=-(dval_ji+ik*sval_ji)
                A1[gj,gi]=-(dval_ji_1+Complex{T}(0,1)*sval_ji+ik*sval_ji_1)
                A2[gj,gi]=-(dval_ji_2+Complex{T}(0,2)*sval_ji_1+ik*sval_ji_2)
            end
        end
    end
    for a in 1:nc,b in 1:nc
        a==b&&continue
        pb=pts[b]
        Pa=parr[a]
        Pb=parr[b]
        Na=length(Pa.X)
        Nb=length(Pb.X)
        ra=offs[a]:(offs[a+1]-1)
        rb=offs[b]:(offs[b+1]-1)
        Xa=Pa.X;Ya=Pa.Y
        Xb=Pb.X;Yb=Pb.Y
        dXb=Pb.dX;dYb=Pb.dY;sb=Pb.s
        @use_threads multithreading=(multithreaded&&Na>=16) for i in 1:Na
            gi=ra[i]
            xi=Xa[i]
            yi=Ya[i]
            @inbounds for j in 1:Nb
                gj=rb[j]
                dx=xi-Xb[j]
                dy=yi-Yb[j]
                r2=muladd(dx,dx,dy*dy)
                r2<=(eps(T))^2&&continue
                r=sqrt(r2)
                invr=inv(r)
                inn=dYb[j]*dx-dXb[j]*dy
                h0,h1=hankel_pair01(k*r)
                sj=sb[j]
                wj=pb.ws[j]
                dval=wj*(Complex{T}(0,k/2)*inn*h1*invr)
                dval1=wj*(-Complex{T}(0,one(T)/2)*inn*k*h0)
                dval2=wj*(-Complex{T}(0,one(T)/2)*inn*(h0-k*r*h1))
                sval=wj*(Complex{T}(0,one(T)/2)*h0*sj)
                sval1=wj*(-Complex{T}(0,one(T)/2)*r*h1*sj)
                sval2=wj*(Complex{T}(0,one(T)/2)*r*(h1-k*r*h0)*sj/k)
                A[gi,gj]=-(dval+ik*sval)
                A1[gi,gj]=-(dval1+Complex{T}(0,1)*sval+ik*sval1)
                A2[gi,gj]=-(dval2+Complex{T}(0,2)*sval1+ik*sval2)
            end
        end
    end
    return A,A1,A2
end

"""
    construct_matrices_reduced_deriv!(solver,A,A1,A2,pts,ws,k;multithreaded=true) → A,A1,A2

Assembles the symmetry-reduced CFIE-Kress matrix and its first two derivatives.

## Description
This is the derivative-aware analogue of
[`construct_matrices_reduced!`](@ref).

For each reduced source degree of freedom, all members of its full-boundary
symmetry orbit are accumulated with their symmetry character or phase factor.

The output matrices are constructed directly in the reduced basis without
forming their full-space counterparts.

## Arguments
* `solver`: CFIE-Kress solver with active symmetry.
* `A`: Destination matrix for the reduced operator.
* `A1`: Destination matrix for the reduced first derivative.
* `A2`: Destination matrix for the reduced second derivative.
* `pts`: Full boundary discretizations.
* `ws`: CFIE-Kress workspace containing the symmetry maps and geometry caches.
* `k`: Real wavenumber.

## Keyword arguments
* `multithreaded`: Whether to thread reduced column assembly.

## Returns
* `A`: Reduced CFIE-Kress matrix.
* `A1`: First derivative.
* `A2`: Second derivative.
"""
function construct_matrices_reduced_deriv!(solver::Union{CFIE_kress,CFIE_kress_corners,CFIE_kress_global_corners},A::AbstractMatrix{Complex{T}},A1::AbstractMatrix{Complex{T}},A2::AbstractMatrix{Complex{T}},pts::Vector{BoundaryPoints{T}},ws::CFIEKressWorkspace{T},k::T;multithreaded::Bool=true) where {T<:Real}
    Nred=ws.Nred
    @assert size(A,1)==Nred&&size(A,2)==Nred
    αL1=-k*inv_two_pi
    αL2=Complex{T}(0,k/2)
    αM1=-inv_two_pi
    αM2=Complex{T}(0,one(T)/2)
    ik=Complex{T}(0,k)
    fill!(A,zero(Complex{T}))
    fill!(A1,zero(Complex{T}))
    fill!(A2,zero(Complex{T}))
    @use_threads multithreading=multithreaded for b in 1:Nred
        orb=ws.reduced_orbits[b]
        imgs=orb.full
        scales=orb.scales
        @inbounds for a in 1:Nred
            gi=ws.Ifund[a]
            ib=ws.global_to_block[gi]
            i=ws.global_to_local[gi]
            acc0=zero(Complex{T})
            acc1=zero(Complex{T})
            acc2=zero(Complex{T})
            for q in eachindex(imgs)
                gj=imgs[q]
                scale=scales[q]
                jb=ws.global_to_block[gj]
                j=ws.global_to_local[gj]
                if ib==jb
                    p=pts[ib]
                    G=ws.Gs[ib]
                    si=G.speed[i]
                    sj=G.speed[j]
                    wi=p.ws[i]
                    wj=p.ws[j]
                    if i==j
                        dval=Complex{T}(wi*G.kappa[i],zero(T))
                        m1=αM1*si
                        m2=((Complex{T}(0,one(T)/2)-euler_over_pi)-inv_two_pi*log((k^2/4)*si^2))*si
                        sval=Complex{T}(ws.Rmat[gi,gj]*m1,zero(T))+wi*m2
                        sval1=wi*(-si/(pi*k))
                        sval2=wi*(si/(pi*k^2))
                        acc0+=scale*(one(Complex{T})-(dval+ik*sval))
                        acc1+=scale*-(Complex{T}(0,1)*sval+ik*sval1)
                        acc2+=scale*-(Complex{T}(0,2)*sval1+ik*sval2)
                    else
                        r=G.R[i,j]
                        invr=G.invR[i,j]
                        lt=G.logterm[i,j]
                        inn=G.inner[i,j]
                        kr=k*r
                        h0,h1=hankel_pair01(kr)
                        j0=real(h0)
                        j1=real(h1)
                        l1=αL1*inn*j1*invr
                        l2=αL2*inn*h1*invr-l1*lt
                        dval=ws.Rmat[gi,gj]*l1+wj*l2
                        l1_1=-(inn*k*j0)*inv_two_pi
                        l1_2=(inn*(k*r*j1-j0))*inv_two_pi
                        l2_1=(inn*k*(lt*j0+im*pi*h0))*inv_two_pi
                        l2_2=(inn*(lt*(j0-k*r*j1)+im*pi*(h0-k*r*h1)))*inv_two_pi
                        dval1=ws.Rmat[gi,gj]*l1_1+wj*l2_1
                        dval2=ws.Rmat[gi,gj]*l1_2+wj*l2_2
                        m1=αM1*j0*sj
                        m2=αM2*h0*sj-m1*lt
                        sval=ws.Rmat[gi,gj]*m1+wj*m2
                        m1_1=(r*sj*j1)*inv_two_pi
                        m1_2=(r*sj*(k*r*j0-j1))*inv_two_pi/k
                        m2_1=-(r*sj*(lt*j1+im*pi*h1))*inv_two_pi
                        m2_2=(r*sj*(lt*(j1-k*r*j0)-im*pi*k*r*h0+im*pi*h1))*inv_two_pi/k
                        sval1=ws.Rmat[gi,gj]*m1_1+wj*m2_1
                        sval2=ws.Rmat[gi,gj]*m1_2+wj*m2_2
                        acc0+=scale*-(dval+ik*sval)
                        acc1+=scale*-(dval1+Complex{T}(0,1)*sval+ik*sval1)
                        acc2+=scale*-(dval2+Complex{T}(0,2)*sval1+ik*sval2)
                    end
                else
                    Pi=ws.parr[ib]
                    Pj=ws.parr[jb]
                    pb=pts[jb]
                    dx=Pi.X[i]-Pj.X[j]
                    dy=Pi.Y[i]-Pj.Y[j]
                    r2=muladd(dx,dx,dy*dy)
                    if r2>(eps(T))^2
                        r=sqrt(r2)
                        invr=inv(r)
                        inn=Pj.dY[j]*dx-Pj.dX[j]*dy
                        h0,h1=hankel_pair01(k*r)
                        sj=Pj.s[j]
                        wj=pb.ws[j]
                        dval=wj*(Complex{T}(0,k/2)*inn*h1*invr)
                        dval1=wj*(-Complex{T}(0,one(T)/2)*inn*k*h0)
                        dval2=wj*(-Complex{T}(0,one(T)/2)*inn*(h0-k*r*h1))
                        sval=wj*(Complex{T}(0,one(T)/2)*h0*sj)
                        sval1=wj*(-Complex{T}(0,one(T)/2)*r*h1*sj)
                        sval2=wj*(Complex{T}(0,one(T)/2)*r*(h1-k*r*h0)*sj/k)
                        acc0+=scale*-(dval+ik*sval)
                        acc1+=scale*-(dval1+Complex{T}(0,1)*sval+ik*sval1)
                        acc2+=scale*-(dval2+Complex{T}(0,2)*sval1+ik*sval2)
                    end
                end
            end
            A[a,b]=acc0
            A1[a,b]=acc1
            A2[a,b]=acc2
        end
    end
    return A,A1,A2
end

"""
    construct_matrices!(solver,A,pts,ws,k;multithreaded=true)
    construct_matrices!(solver,A,pts,Rmat,k;multithreaded=true)
    construct_matrices!(solver,A,A1,A2,pts,ws,k;multithreaded=true)
    construct_matrices!(solver,A,A1,A2,pts,Rmat,k;multithreaded=true)

High-level CFIE-Kress matrix assembly interface.

## Description
These overloads select automatically between full and symmetry-reduced
assembly.

When a cached [`CFIEKressWorkspace`](@ref) is supplied, all geometric quantities
and symmetry maps are reused.

When only `Rmat` is supplied, geometry caches and flattened panel arrays are
constructed from `pts` for the current call.

The assembled operator is

    A(k)=I-(D(k)+ikS(k)).

Derivative overloads additionally return its first two derivatives with respect
to `k`.

## Arguments
* `solver`: CFIE-Kress solver.
* `A`: Destination matrix for the operator.
* `A1`: Destination matrix for the first derivative.
* `A2`: Destination matrix for the second derivative.
* `pts`: Boundary discretizations.
* `ws`: Optional cached CFIE-Kress workspace.
* `Rmat`: Optional precomputed Kress logarithmic correction matrix.
* `basis`: Placeholder Hankel basis used by the common solver API.
* `k`: Real wavenumber.

## Keyword arguments
* `multithreaded`: Whether to thread low-level matrix assembly.

## Returns
* Matrix-only forms return `A`.
* Derivative forms return `(A,A1,A2)`.
"""
function construct_matrices!(solver::Union{CFIE_kress,CFIE_kress_corners,CFIE_kress_global_corners},A::AbstractMatrix{Complex{T}},pts::Vector{BoundaryPoints{T}},ws::CFIEKressWorkspace{T},k::T;multithreaded::Bool=true) where {T<:Real}
    if isnothing(ws.symmetry)
        @blas_1 construct_matrices!(solver,A,pts,ws.Rmat,ws.Gs,ws.parr,ws.offs,k;multithreaded=multithreaded)
    else
        @blas_1 construct_matrices_reduced!(solver,A,pts,ws,k;multithreaded=multithreaded)
    end
    return A
end

function construct_matrices!(solver::Union{CFIE_kress,CFIE_kress_corners,CFIE_kress_global_corners},A::AbstractMatrix{Complex{T}},pts::Vector{BoundaryPoints{T}},Rmat::AbstractMatrix{T},k::T;multithreaded::Bool=true) where {T<:Real}
    offs=component_offsets(pts)
    Gs=[boundary_geom_cache(p,_is_nontrivial_grading(p)) for p in pts]
    parr=[_boundary_panel_arrays_cache(p) for p in pts]
    return construct_matrices!(solver,A,pts,Rmat,Gs,parr,offs,k;multithreaded=multithreaded)
end

function construct_matrices!(solver::Union{CFIE_kress,CFIE_kress_corners,CFIE_kress_global_corners},A::AbstractMatrix{Complex{T}},A1::AbstractMatrix{Complex{T}},A2::AbstractMatrix{Complex{T}},pts::Vector{BoundaryPoints{T}},ws::CFIEKressWorkspace{T},k::T;multithreaded::Bool=true) where {T<:Real}
    if isnothing(ws.symmetry)
        construct_matrices!(solver,A,A1,A2,pts,ws.Rmat,ws.Gs,ws.parr,ws.offs,k;multithreaded=multithreaded)
    else
        construct_matrices_reduced_deriv!(solver,A,A1,A2,pts,ws,k;multithreaded=multithreaded)
    end
    return A,A1,A2
end

function construct_matrices!(solver::Union{CFIE_kress,CFIE_kress_corners,CFIE_kress_global_corners},A::AbstractMatrix{Complex{T}},A1::AbstractMatrix{Complex{T}},A2::AbstractMatrix{Complex{T}},pts::Vector{BoundaryPoints{T}},Rmat::AbstractMatrix{T},k::T;multithreaded::Bool=true) where {T<:Real}
    offs=component_offsets(pts)
    Gs=[boundary_geom_cache(p,_is_nontrivial_grading(p)) for p in pts]
    parr=[_boundary_panel_arrays_cache(p) for p in pts]
    return construct_matrices!(solver,A,A1,A2,pts,Rmat,Gs,parr,offs,k;multithreaded=multithreaded)
end

function construct_matrices!(solver::Union{CFIE_kress,CFIE_kress_corners,CFIE_kress_global_corners},basis::AbstractHankelBasis,A::AbstractMatrix{Complex{T}},dA::AbstractMatrix{Complex{T}},ddA::AbstractMatrix{Complex{T}},pts::Vector{BoundaryPoints{T}},k::T;multithreaded::Bool=true) where {T<:Real}
    ws=build_cfie_kress_workspace(solver,pts)
    construct_matrices!(solver,A,dA,ddA,pts,ws,k;multithreaded=multithreaded)
    return A,dA,ddA
end

function construct_matrices!(solver::Union{CFIE_kress,CFIE_kress_corners,CFIE_kress_global_corners},basis::AbstractHankelBasis,A::AbstractMatrix{Complex{T}},dA::AbstractMatrix{Complex{T}},ddA::AbstractMatrix{Complex{T}},pts::Vector{BoundaryPoints{T}},ws::CFIEKressWorkspace{T},k::T;multithreaded::Bool=true) where {T<:Real}
    construct_matrices!(solver,A,dA,ddA,pts,ws,k;multithreaded=multithreaded)
    return A,dA,ddA
end

"""
    solve(solver,basis,pts,k;multithreaded=true,use_krylov=true,which=:det)
    solve(solver,basis,pts,ws,k;multithreaded=true,use_krylov=true,which=:det_argmin)
    solve(solver,basis,A,pts,ws,k;multithreaded=true,use_krylov=true,which=:det_argmin)

Evaluates a scalar spectral diagnostic of the CFIE-Kress operator.

## Description
The matrix

    A(k)=I-(D(k)+ikS(k))

is assembled and passed to the common SVD/determinant reduction backend.

The overloads differ only in how much memory and geometry information is reused.

## Arguments
* `solver`: CFIE-Kress solver.
* `basis`: Basis placeholder retained for the common solver interface.
* `pts`: Boundary discretizations.
* `ws`: Optional cached CFIE-Kress workspace.
* `A`: Optional preallocated matrix buffer.
* `k`: Real wavenumber.

## Keyword arguments
* `multithreaded`: Whether to thread matrix assembly.
* `use_krylov`: Selects the Krylov pathway where supported by the reduction
  backend.
* `which`: Scalar spectral diagnostic requested from the common backend.

## Returns
A scalar spectral diagnostic whose interpretation depends on `which`.
"""
function solve(solver::Union{CFIE_kress,CFIE_kress_corners,CFIE_kress_global_corners},basis::Ba,pts::Vector{BoundaryPoints{T}},k;multithreaded::Bool=true,use_krylov::Bool=true,which::Symbol=:det) where {T<:Real,Ba<:AbsBasis}
    ws=build_cfie_kress_workspace(solver,pts)
    N=isnothing(ws.symmetry) ? ws.Ntot : ws.Nred
    A=Matrix{Complex{T}}(undef,N,N)
    @blas_1 construct_matrices!(solver,A,pts,ws,k;multithreaded=multithreaded)
    @svd_or_det_solve A use_krylov which MAX_BLAS_THREADS
end

function solve(solver::Union{CFIE_kress,CFIE_kress_corners,CFIE_kress_global_corners},basis::Ba,pts::Vector{BoundaryPoints{T}},ws::CFIEKressWorkspace{T},k;multithreaded::Bool=true,use_krylov::Bool=true,which::Symbol=:det_argmin) where {T<:Real,Ba<:AbsBasis}
    N=isnothing(ws.symmetry) ? ws.Ntot : ws.Nred
    A=Matrix{Complex{T}}(undef,N,N)
    @blas_1 construct_matrices!(solver,A,pts,ws,k;multithreaded=multithreaded)
    @svd_or_det_solve A use_krylov which MAX_BLAS_THREADS
end

function solve(solver::Union{CFIE_kress,CFIE_kress_corners,CFIE_kress_global_corners},basis::Ba,A::AbstractMatrix{Complex{T}},pts::Vector{BoundaryPoints{T}},ws::CFIEKressWorkspace{T},k;multithreaded::Bool=true,use_krylov::Bool=true,which::Symbol=:det_argmin) where {T<:Real,Ba<:AbsBasis}
    @blas_1 construct_matrices!(solver,A,pts,ws,k;multithreaded=multithreaded)
    @svd_or_det_solve A use_krylov which MAX_BLAS_THREADS
end

# TODO: The multi-k solve_vect pathway should eventually dispatch to the
# Chebyshev-interpolated matrix construction.

"""
    solve_vect(solver,basis,A,pts,ws,k;multithreaded=true,tol=1e-12,maxiter=2000,krylovdim=40)
    solve_vect(solver,basis,pts,ws,k;multithreaded=true,tol=1e-12,maxiter=2000,krylovdim=40)
    solve_vect(solver,billiard,basis,pts,k;multithreaded=true,tol=1e-12,maxiter=2000,krylovdim=40)

Computes a near-null vector of the CFIE-Kress matrix.

## Description
The CFIE matrix is assembled and passed to
[`smallest_nullvec_krylov!`](@ref).

That routine applies a Krylov eigensolver to the inverse operator, so the
returned scalar is an inverse-eigenvalue-based spectral proximity proxy rather
than an exact smallest singular value in general.

Near a genuine simple zero of the Fredholm operator, the corresponding vector
approaches the physical null vector required for boundary-state
postprocessing.

## Arguments
* `solver`: CFIE-Kress solver.
* `basis`: Basis placeholder retained for API compatibility.
* `A`: Optional preallocated matrix buffer.
* `pts`: Boundary discretizations.
* `ws`: Cached CFIE-Kress workspace.
* `billiard`: Billiard geometry, retained by the convenience overload.
* `k`: Real wavenumber.

## Keyword arguments
* `multithreaded`: Whether to thread matrix assembly.
* `tol`: Krylov convergence tolerance.
* `maxiter`: Maximum number of Krylov iterations.
* `krylovdim`: Krylov subspace dimension.

## Returns
* `σ`: Small-eigenvalue/spectral-proximity proxy returned by
  [`smallest_nullvec_krylov!`](@ref).
* `u`: Corresponding normalized near-null vector.
"""
function solve_vect(solver::Union{CFIE_kress,CFIE_kress_corners,CFIE_kress_global_corners},basis::Ba,A::AbstractMatrix{Complex{T}},pts::Vector{BoundaryPoints{T}},ws::CFIEKressWorkspace{T},k;multithreaded::Bool=true,tol=1e-12,maxiter::Int=2000,krylovdim::Int=40) where {T<:Real,Ba<:AbsBasis}
    @blas_1 construct_matrices!(solver,A,pts,ws,k;multithreaded=multithreaded)
    σ,u,_=smallest_nullvec_krylov!(A;nev=1,tol=tol,maxiter=maxiter,krylovdim=krylovdim)
    return σ,u
end

function solve_vect(solver::Union{CFIE_kress,CFIE_kress_corners,CFIE_kress_global_corners},basis::Ba,pts::Vector{BoundaryPoints{T}},ws::CFIEKressWorkspace{T},k;multithreaded::Bool=true,tol=1e-12,maxiter::Int=2000,krylovdim::Int=40) where {T<:Real,Ba<:AbsBasis}
    N=isnothing(ws.symmetry) ? ws.Ntot : ws.Nred
    A=Matrix{Complex{T}}(undef,N,N)
    return solve_vect(solver,basis,A,pts,ws,k;multithreaded=multithreaded,tol=tol,maxiter=maxiter,krylovdim=krylovdim)
end

function solve_vect(solver::Union{CFIE_kress,CFIE_kress_corners,CFIE_kress_global_corners},billiard::Bi,basis::Ba,pts::Vector{BoundaryPoints{T}},k;multithreaded::Bool=true,tol=1e-12,maxiter::Int=2000,krylovdim::Int=40) where {T<:Real,Ba<:AbsBasis,Bi<:AbsBilliard}
    ws=build_cfie_kress_workspace(solver,pts)
    return solve_vect(solver,basis,pts,ws,k;multithreaded=multithreaded,tol=tol,maxiter=maxiter,krylovdim=krylovdim)
end

# INTERNAL - for benchmarking and diagnostics only; not part of the public API.
function solve_INFO(solver::Union{CFIE_kress,CFIE_kress_corners,CFIE_kress_global_corners},basis::Ba,pts::Vector{BoundaryPoints{T}},ws::CFIEKressWorkspace{T},k;multithreaded::Bool=true,use_krylov::Bool=true,which::Symbol=:det_argmin) where {T<:Real,Ba<:AbsBasis}
    N=isnothing(ws.symmetry) ? ws.Ntot : ws.Nred
    A=Matrix{Complex{T}}(undef,N,N)
    t0=time()
    @info "Building boundary operator A from cached Kress workspace..."
    @blas_1 construct_matrices!(solver,A,pts,ws,k;multithreaded=multithreaded)
    t1=time()
    cA=cond(A)
    @info "Condition number of A: $(round(cA;sigdigits=4))"
    t2=time()
    s=@svd_or_det_solve A use_krylov which MAX_BLAS_THREADS
    t3=time()
    build_A=t1-t0
    svd_time=t3-t2
    total=build_A+svd_time
    println("────────── SOLVE_INFO SUMMARY ──────────")
    println("A-matrix build: ",100*build_A/total," %")
    println("SVD: ",100*svd_time/total," %")
    println("(total: ",total," s)")
    println("────────────────────────────────────────")
    return s
end