# SmoothPeriodicGrading.jl
#
# Smooth periodic node redistribution for Kress-type Nyström discretizations.
# Requires FFTW. Does not require Statistics.
#
# Mathematical idea:
#   Kress quadrature remains periodic in the uniform computational variable σ.
#   We only change the physical curve parameter by θ=W(σ), with W smooth,
#   periodic, monotone, and derivative-controlled. The logarithmic correction
#   matrix is still built in σ, while geometry derivatives are transformed by
#
#       γσ  = γθ W′,
#       γσσ = γθθ(W′)^2 + γθ W″.
#
# This is the smooth-boundary analogue of Kress corner grading: use a smooth
# substitution, but here the goal is improved resolution rather than endpoint
# singularity removal. Useful for smooth curves with high curvature variation, 
# where the optimal node distribution is not known a priori.

const two_pi=2*pi

"""
    SmoothPeriodicGrading(;fourier_modes=12,speed_strength=0.8,
        curvature_strength=0.05,oversample=16,alpha_speed=0.5,alpha_curv=0.25)

Controls a smooth periodic reparametrization for Kress Nyström nodes.
The computational Kress variable remains uniform,

    σ_j = 2π(j-1)/N,

but the curve is evaluated at a redistributed physical parameter

    θ_j = W(σ_j).

The map is generated by equidistributing a positive monitor density

    ρ(θ)=1+c_s(|γ'(θ)|/max|γ'|)^αs+c_κ κ̃(θ)^ακ,

where `κ̃` is a soft-clipped curvature monitor. The monitor is Fourier-smoothed
before inversion, which prevents sharp derivative spikes in `W`.

The chain rule is used,

    γ_σ  = γ_θ W',
    γ_σσ = γ_θθ(W')² + γ_θ W'',

so diagonal curvature limits remain consistent with the graded parametrization.

# Keyword arguments
- `fourier_modes::Int=12`: Number of Fourier modes retained when smoothing the
  monitor density. Smaller values give smoother, safer grading; larger values
  allow more localized node clustering.
- `speed_strength=0.8`: Strength `c_s` of the speed/arclength monitor. This is
  the main and safest redistribution parameter.
- `curvature_strength=0.05`: Strength `c_κ` of the curvature monitor. Keep this
  small; curvature spikes can otherwise create oscillatory derivatives.
- `oversample::Int=16`: Fine-grid factor used to construct and invert the
  cumulative monitor. This does not change the final matrix size.
- `alpha_speed=0.5`: Exponent `αs` for the speed monitor. Values below one make
  the grading milder.
- `alpha_curv=0.25`: Exponent `ακ` for the soft-clipped curvature monitor.

# Usage
Use this for smooth closed curves where uniform parameter nodes waste resolution
in easy regions and underresolve high-speed or high-curvature regions.

# Notes
This is not corner grading. It assumes the boundary is already smooth and
periodic. For actual corners, use the Kress corner/global grading machinery.
"""
struct SmoothPeriodicGrading{T<:Real}
    fourier_modes::Int
    speed_strength::T
    curvature_strength::T
    oversample::Int
    alpha_speed::T
    alpha_curv::T
end

function SmoothPeriodicGrading(;fourier_modes=12,speed_strength=1.0,curvature_strength=0.0,oversample=32,alpha_speed=1.0,alpha_curv=0.25)
    T=promote_type(typeof(speed_strength),typeof(curvature_strength),typeof(alpha_speed),typeof(alpha_curv))
    return SmoothPeriodicGrading{T}(fourier_modes,T(speed_strength),T(curvature_strength),oversample,T(alpha_speed),T(alpha_curv))
end

# Return integer Fourier frequencies for an N-point 2π-periodic grid.
#
# These are the mode numbers m corresponding to exp(imθ). For even N we suppress
# the Nyquist derivative mode by setting it to zero, which avoids an ambiguous
# purely alternating derivative component.
function periodic_frequency_indices(N::Int)
    k=Vector{Int}(undef,N)
    @inbounds for m in 0:N-1
        q=m<=N÷2 ? m : m-N
        if iseven(N) && m==N÷2
            q=0
        end
        k[m+1]=q
    end
    return k
end

# Spectral derivative of a 2π-periodic function sampled on a uniform grid.
#
# If f(θ)=Σ f_m exp(imθ), then f′(θ)=Σ im f_m exp(imθ).
# This is used to compute ρ′ after Fourier smoothing, avoiding noisy finite
# differences in W″.
function spectral_derivative_2π(f::AbstractVector{<:Real})
    N=length(f)
    k=periodic_frequency_indices(N)
    F=fft(Float64.(f))
    return real.(ifft((im.*k).*F))
end

# Fourier low-pass filter for a positive monitor density.
#
# The raw density may contain sharp curvature spikes. Truncating to a small
# number of Fourier modes gives a smooth periodic monitor. Positivity is enforced
# after filtering and the mean is normalized to one.
function smooth_positive_density(f::AbstractVector{<:Real},modes::Int;floor_fraction=1e-8)
    N=length(f)
    k=periodic_frequency_indices(N)
    F=fft(Float64.(f))
    G=zeros(ComplexF64,N)
    @inbounds for i in 1:N
        abs(k[i])<=modes && (G[i]=F[i])
    end
    g=real.(ifft(G))
    μ=sum(g)/N
    floorv=floor_fraction*max(abs(μ),eps(Float64))
    g=max.(g,floorv)
    g./=(sum(g)/N)
    return g
end

# Quantile helper without Statistics.jl.
#
# Used only for soft-clipping curvature. Linear interpolation between sorted
# order statistics matches the usual quantile behavior well enough here.
function sorted_quantile(v::AbstractVector{<:Real},q::Real)
    isempty(v) && error("Cannot compute quantile of an empty vector.")
    w=sort(Float64.(v))
    n=length(w)
    n==1 && return w[1]
    x=clamp(q,0,1)*(n-1)+1
    i=floor(Int,x)
    a=x-i
    i>=n && return w[n]
    return (1-a)*w[i]+a*w[i+1]
end

# Periodic linear interpolation on an equispaced θ-grid.
#
# This evaluates ρ(W(σ)) and ρ′(W(σ)) after inversion of the cumulative map.
# Interpolating avoids the piecewise-constant derivative noise that would appear
# if one used only the nearest fine-grid density value.
@inline function periodic_linear_interpolate(vals::AbstractVector{T},θ::Real,dθ::Real) where {T}
    M=length(vals)
    x=mod(θ,two_pi)/dθ
    i0=floor(Int,x)+1
    a=x-(i0-1)
    i1=i0==M ? 1 : i0+1
    return (1-a)*vals[i0]+a*vals[i1]
end

# Compute geometry monitors on a fine periodic θ-grid.
#
# speed_norm = |γθ|/max|γθ| gives arclength-aware redistribution.
#
# κsoft is a clipped curvature monitor:
#   κsoft = clamp(|κ|/quantile(|κ|,0.95),0,1).
#
# The clipping prevents isolated curvature spikes from creating a sharp W′ dip,
# which would be bad for spectral Kress convergence.
function compute_speed_and_curvature(crv,M::Int)
    θ=collect((0:M-1).*(two_pi/M))
    t=θ./two_pi
    γθ=tangent(crv,t)./two_pi
    γθθ=tangent_2(crv,t)./two_pi^2
    speed=[hypot(v[1],v[2]) for v in γθ]
    κ=abs.([(γθ[i][1]*γθθ[i][2]-γθ[i][2]*γθθ[i][1])/(speed[i]^3+eps(Float64)) for i in eachindex(speed)])
    speed_norm=maximum(speed)>0 ? speed./maximum(speed) : ones(Float64,M)
    κ95=sorted_quantile(κ,0.95)
    κsoft=κ95>0 ? clamp.(κ./κ95,0.0,1.0) : zeros(Float64,M)
    return θ,speed_norm,κsoft
end

# Build the smooth substitution σ -> θ=W(σ).
#
# Equidistribution condition:
#   σ/(2π) = ∫₀^{W(σ)}ρ(θ)dθ / ∫₀^{2π}ρ(θ)dθ.
#
# Differentiating gives
#   W′  = ρmean/ρ(W),
#   W″  = -ρmean² ρ′(W)/ρ(W)³.
#
# These analytic derivative formulas are the key point: they give smooth
# chain-rule data for the Kress diagonal/self terms.
function build_reparametrization_map(crv,N::Int,grading::SmoothPeriodicGrading)
    M=grading.oversample*N
    _,speed,κ=compute_speed_and_curvature(crv,M)
    cs=clamp(Float64(grading.speed_strength),0.0,1.0)
    speedpow=@. speed^grading.alpha_speed
    ρspeed=@. (1-cs)+cs*speedpow
    ρcurv=@. 1+grading.curvature_strength*κ^grading.alpha_curv
    ρraw=@. ρspeed*ρcurv
    ρ=smooth_positive_density(ρraw,grading.fourier_modes)
    ρ′=spectral_derivative_2π(ρ)
    dθ=two_pi/M
    C=zeros(Float64,M+1)
    @inbounds for i in 1:M
        C[i+1]=C[i]+ρ[i]*dθ
    end
    total=C[end]
    C./=total
    ρmean=total/two_pi
    σ=collect((0:N-1).*(two_pi/N))
    θ=zeros(Float64,N)
    Wp=zeros(Float64,N)
    Wpp=zeros(Float64,N)
    @inbounds for j in 1:N
        q=σ[j]/two_pi
        i=clamp(searchsortedlast(C,q),1,M)
        a=(q-C[i])/(C[i+1]-C[i])
        θ[j]=(i-1+a)*dθ
        ρj=periodic_linear_interpolate(ρ,θ[j],dθ)
        ρpj=periodic_linear_interpolate(ρ′,θ[j],dθ)
        Wp[j]=ρmean/ρj
        Wpp[j]=-(ρmean^2)*ρpj/(ρj^3)
    end
    return σ,θ,Wp,Wpp
end