"""
    elliptic_arc(A,B,b;origin=(0,0),rot_angle=0)

Construct one elliptic arc joining vertices `A` and `B`.

The arc is chosen so that:
- `A` and `B` are the endpoints,
- the minor semi-axis is `b`,
- the major semi-axis is determined from the endpoint separation.

Returns a `PolarSegment`.
"""
function elliptic_arc(A::SVector{2,T},B::SVector{2,T},b::T;
    origin=zero(A),rot_angle=zero(T)) where {T<:Real}
    C=(A+B)/2
    d=norm(B-A)
    c=d/2
    a=sqrt(b^2+c^2)
    u=(B-A)/d
    v=SVector(-u[2],u[1])
    r_func=t->begin
        θ=pi*(t-0.5)
        C+a*cos(θ)*u+b*sin(θ)*v
    end
    return PolarSegment(r_func;origin=origin,rot_angle=rot_angle)
end

"""
    make_elliptic_flower_component(n,Rb,b;θ0=0,origin=(0,0),rot_angle=0)

Construct the full elliptic flower outer boundary with `n` petals.

The vertices are the regular `n`-gon vertices of circumradius `Rb`, and the
j-th petal is the elliptic arc joining vertex `j` to vertex `j+2`.

Returns `(boundary,vertices)`.
"""
function make_elliptic_flower_component(n::Int,Rb::T,b::T;
    θ0=zero(T),origin=(0.0,0.0),rot_angle=zero(T)) where {T<:Real}
    verts=[SVector{2,T}(Rb*cos(θ0+2π*j/n),Rb*sin(θ0+2π*j/n)) for j in 0:n-1]
    boundary=AbsRealCurve[]
    for j in 1:n
        A=verts[j]
        B=verts[mod1(j+2,n)]
        push!(boundary,elliptic_arc(A,B,b;origin=origin,rot_angle=rot_angle))
    end
    return boundary,verts
end

"""
    make_desymmetrized_elliptic_flower_component(n,Rb,b;θ0=0,origin=(0,0),rot_angle=0)

Construct one fundamental-domain outer boundary piece for the elliptic flower.

Since the full flower is generated by Cₙ rotation, the fundamental boundary is
just one elliptic arc, namely the first one joining vertex 1 to vertex 3.

Returns `(boundary,vertices)` where `boundary` is a one-element vector.
"""
function make_desymmetrized_elliptic_flower_component(n::Int,Rb::T,b::T;
    θ0=zero(T),origin=(0.0,0.0),rot_angle=zero(T)) where {T<:Real}
    verts=[SVector{2,T}(Rb*cos(θ0+2π*j/n),Rb*sin(θ0+2π*j/n)) for j in 0:n-1]
    A=verts[1]
    B=verts[mod1(3,n)]
    boundary=AbsRealCurve[elliptic_arc(A,B,b;origin=origin,rot_angle=rot_angle)]
    return boundary,verts
end

"""
    make_polygon_hole_component(n,Rh;θ0=0,origin=(0,0),rot_angle=0)

Construct a full regular `n`-gon hole of circumradius `Rh`.

Returns `(boundary,vertices)`.
"""
function make_polygon_hole_component(n::Int,Rh::T;
    θ0=zero(T),origin=(0.0,0.0),rot_angle=zero(T)) where {T<:Real}
    verts=[SVector{2,T}(Rh*cos(θ0+2π*j/n),Rh*sin(θ0+2π*j/n)) for j in 0:n-1]
    edges=[LineSegment(verts[i],verts[mod1(i+1,n)];origin=origin,rot_angle=rot_angle) for i in 1:n]
    return edges,verts
end

"""
    make_desymmetrized_polygon_hole_component(n,Rh;θ0=0,origin=(0,0),rot_angle=0)

Construct one fundamental-domain edge of a regular `n`-gon hole.

Returns `(boundary,vertices)` where `boundary` is a one-element vector.
"""
function make_desymmetrized_polygon_hole_component(n::Int,Rh::T;
    θ0=zero(T),origin=(0.0,0.0),rot_angle=zero(T)) where {T<:Real}
    verts=[SVector{2,T}(Rh*cos(θ0+2π*j/n),Rh*sin(θ0+2π*j/n)) for j in 0:n-1]
    edge=LineSegment(verts[2],verts[1];origin=origin,rot_angle=rot_angle)
    return AbsRealCurve[edge],verts
end

@inline function _boundary_total_length(boundary)
    if boundary isa Vector{<:AbstractVector}
        return sum(sum(crv.length for crv in comp) for comp in boundary)
    else
        return sum(crv.length for crv in boundary)
    end
end

@inline function _regular_ngon_area(n::Int,R::T) where {T<:Real}
    return T(n)*R^2*sin(T(2π/n))/2
end

"""
    EllipticFlowerWithOptionalHole{T}

Elliptic flower billiard with optional regular polygon hole.

Boundary convention:
- no hole:
    `full_boundary = outer_full`
    `desymmetrized_full_boundary = outer_desym`
- with hole:
    `full_boundary = [outer_full,inner_full]`
    `desymmetrized_full_boundary = [outer_desym,inner_desym]`
"""
struct EllipticFlowerWithOptionalHole{T}<:AbsBilliard where {T<:Real}
    full_boundary
    desymmetrized_full_boundary
    length::T
    length_fundamental::T
    area::T
    area_fundamental::T
    n::Int
    Rb::T
    b::T
    hole_radius::Union{Nothing,T}
    vertices_outer::Vector{SVector{2,T}}
    vertices_inner::Union{Nothing,Vector{SVector{2,T}}}
    angles::Vector{T}
    angles_fundamental::Vector{T}
end

"""
    EllipticFlowerWithOptionalHole(n;Rb=1.0,b=0.4,hole=false,hole_radius=nothing,hole_scale=0.35,θ0=0)

Construct an elliptic flower billiard with `n`-fold rotational symmetry and an
optional regular `n`-gon hole.

Arguments:
- `n`: number of petals / rotation order
- `Rb`: circumradius of the outer vertex polygon
- `b`: minor semi-axis parameter of each elliptic petal
- `hole`: whether to include a polygon hole
- `hole_radius`: circumradius of the polygon hole; overrides `hole_scale`
- `hole_scale`: if `hole_radius===nothing`, use `hole_scale*Rb`
- `θ0`: global angular offset

Returns `EllipticFlowerWithOptionalHole`.
"""
function EllipticFlowerWithOptionalHole(n::Int;Rb=1.0,b=0.4,hole::Bool=false,hole_radius=nothing,hole_scale=0.35,θ0=0.0)
    outer_full,verts_outer=make_elliptic_flower_component(n,Rb,b;θ0=θ0)
    outer_desym,_=make_desymmetrized_elliptic_flower_component(n,Rb,b;θ0=θ0)
    if hole
        Rh=hole_radius===nothing ? hole_scale*Rb : hole_radius
        inner_full,verts_inner=make_polygon_hole_component(n,Rh;θ0=θ0)
        inner_desym,_=make_desymmetrized_polygon_hole_component(n,Rh;θ0=θ0)
        full_boundary=[outer_full,inner_full]
        desymmetrized_full_boundary=[outer_desym,inner_desym]
        hole_radius_val=Rh
        vertices_inner_val=verts_inner
    else
        full_boundary=outer_full
        desymmetrized_full_boundary=outer_desym
        hole_radius_val=nothing
        vertices_inner_val=nothing
    end
    length=_boundary_total_length(full_boundary)
    length_fundamental=_boundary_total_length(desymmetrized_full_boundary)
    outer_area=zero(Float64)
    inner_area=(hole && hole_radius_val!==nothing) ? _regular_ngon_area(n,hole_radius_val) : zero(Float64)
    area=outer_area-inner_area
    area_fundamental=area/Float64(n)
    angles=Float64[]
    angles_fundamental=Float64[]
    return EllipticFlowerWithOptionalHole(full_boundary,desymmetrized_full_boundary,
        Float64(length),
        Float64(length_fundamental),
        Float64(area),
        Float64(area_fundamental),
        n,
        Float64(Rb),
        Float64(b),
        hole_radius_val,
        verts_outer,
        vertices_inner_val,
        angles,
        angles_fundamental)
end

############################
#### BASIS HELPER ##########
############################

"""
    make_elliptic_flower_and_basis(n;
        Rb=1.0,b=0.4,hole=false,hole_radius=nothing,hole_scale=0.35,
        θ0=0,basis_type=:cafb,m=0)

Construct the elliptic flower billiard together with a rotationally adapted basis.

Arguments:
- `n`: rotation order
- `m`: rotational irrep index for `Rotation(n,m,(0,0))`

Returns `(billiard,basis)`.
"""
function make_elliptic_flower_and_basis(n::Int;Rb=1.0,b=0.4,hole=false,hole_radius=nothing,hole_scale=0.35,θ0=0.0,m::Int=0)
    billiard=EllipticFlowerWithOptionalHole(n;Rb=Rb,b=b,hole=hole,hole_radius=hole_radius,hole_scale=hole_scale,θ0=θ0)
    symmetry=Vector{Any}([Rotation(n,m,(0.0,0.0))])
    basis=AbstractHankelBasis()
    return billiard,basis
end